### ISSUE TITLE
Set the order of maven goals to be executed 

### ISSUE THREAD

**Issue by hzitoun** [Angular2Guy/Angular2AndJavaEE#2]
The order of **maven** **goals** to execute using `mvn `command line in order to build the app (front-end and back-end) is missing.

**Comment by Angular2Guy** [comment]
The order of the maven goals is set by maven. To build the application execute 'mvn clean install'. The backend and the frontend are build in one ear in one build. Is something missing?

**Comment by Angular2Guy** [comment]
Is no bug.
